---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
library(tidyverse)
```

```{r}
library(readr)
library(tidyverse)
BasicCompanyDataAsOneFile_2020_10_01 <- read_csv("raw_data/BasicCompanyDataAsOneFile-2020-10-01.csv", 
    col_types = cols_only(CompanyCategory = col_guess(), 
        CompanyName = col_guess(), CompanyNumber = col_guess(), 
        CompanyStatus = col_guess(), CountryOfOrigin = col_guess(), 
        IncorporationDate = col_guess(), 
        RegAddress.AddressLine1 = col_guess(), 
        RegAddress.AddressLine2 = col_guess(), 
        RegAddress.CareOf = col_guess(), 
        RegAddress.Country = col_guess(), 
        RegAddress.County = col_guess(), 
        RegAddress.POBox = col_guess(), RegAddress.PostCode = col_guess(), 
        RegAddress.PostTown = col_guess(), 
        SICCode.SicText_1 = col_guess(), 
        SICCode.SicText_2 = col_guess(), 
        SICCode.SicText_3 = col_guess(), 
        SICCode.SicText_4 = col_guess(), 
        URI = col_guess()))
View(BasicCompanyDataAsOneFile_2020_10_01)
```

```{r}
BasicCompanyDataAsOneFile_2020_10_01 %>% 
    filter(RegAddress.Country == "SCOTLAND")
```

